// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

enum ProjectType {
  project1,
  project2,
}

class DefaultFirebaseOptions {
  static FirebaseOptions currentPlatform({
    ProjectType projectType = ProjectType.project1,
  }) {
    if (kIsWeb) {
      if (projectType == ProjectType.project1) return webProject1;
      return webProject2;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions webProject2 = FirebaseOptions(
    apiKey: 'AIzaSyAfIGXVCzncwp5YAVZNHq1ItFU83CaKK2k',
    appId: '1:238064588163:web:41a6898ce32f1cb663d2b6',
    messagingSenderId: '238064588163',
    projectId: 'project2-3fa19',
    authDomain: 'project2-3fa19.firebaseapp.com',
    storageBucket: 'project2-3fa19.appspot.com',
  );

  static const FirebaseOptions webProject1 = FirebaseOptions(
    apiKey: 'AIzaSyCQRjOJE5sQ02ohliIzOKZKwyFPsFbGcXI',
    appId: '1:1066468374177:web:5c0aa5a9e7c838ba0962e0',
    messagingSenderId: '1066468374177',
    projectId: 'project1-869ed',
    authDomain: 'project1-869ed.firebaseapp.com',
    storageBucket: 'project1-869ed.appspot.com',
  );
}
